{% set name = "MicroED tools" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "0.1.0-dev.7" %}

package:
  name: {{ tarname }}
  version: {{ version|replace('-dev.', '.dev') }}

source:
  url: https://cryoem.ucla.edu/downloads/{{ tarname }}-{{ version }}.tar.gz
  sha256: 1f8a603a3f805a77f5c167f02422dde3a62afa51014ae346e4d473e21480a0fd
  patches:
    - 01-nlopt-conda.patch  # [win]

build:
  ignore_run_exports:
    - numpy
    - python
  ignore_run_exports_from:
    - {{ compiler('cxx') }}  # [not osx]
  number: 0
  script_env:
    - USER                   # [unix]
    - USERNAME               # [win]
  skip: True                 # [py==39 and python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake          >=3.15,<4
    - coreutils                    # [unix]
    - cython         >=0.27.1
    - flex           >=2.5.34,<3   # [unix]
    - libxslt        >=0.13.0
    - m2-coreutils                 # [win]
    - m2-sed                       # [win]
    - make                         # [unix]
    - pandoc         2.*
    - pkg-config                   # [unix]
    - winflexbison   >=2.2,<3      # [win]
  host:
    - libarchive     >=2.8.0,<4
    - libiconv                     # [win]
    - libtiff        4.*
    - libxml2        >=2.1,<3
    - nlopt          2.*
    - numpy          >=1.7,<2
    - pthreads-win32               # [win]
    - python         {{ python }}
  run:
    - libarchive
    - libiconv                     # [win]
    - libtiff
    - libxml2
    - nlopt
    - numpy
    - pthreads-win32               # [win]
    - python

test:
  imports:
    - pysmv
  requires:
    - coreutils                         # [unix]
    - m2-coreutils                      # [win]
    - m2-sed                            # [win]
    - microed-data >=0.1.0.dev4,<0.2.0

about:
  home: https://cryoem.ucla.edu/microed
  license: ISC
  license_file: LICENSE
  summary: "Convert electron diffraction images to SMV format"
  description: |
    The MicroED tools convert sequences of related electron
    diffraction images, or MicroED sweeps, to the Super Marty View
    (SMV) format.

extra:
  recipe-maintainers:
    - hattne
